agnostic_nms: false
amp: true
augment: false
auto_augment: randaugment
batch: 16
bgr: 0.0
box: 10.0
cache: false
cfg: null
classes: null
close_mosaic: 50
cls: 0.5
conf: 0.3
copy_paste: 0.0
copy_paste_mode: flip
cos_lr: true
cutmix: 0.0
data: data.yaml
degrees: 5.0
deterministic: true
device:
- 0
dfl: 1.5
dnn: false
dropout: 0.0
dynamic: false
embed: null
epochs: 300
erasing: 0.1
exist_ok: false
fliplr: 0.5
flipud: 0.0
format: torchscript
fraction: 1.0
freeze: 20.0
half: false
hsv_h: 0.015
hsv_s: 0.3
hsv_v: 0.3
imgsz: 640
int8: false
iou: 0.8
keras: false
kobj: 1.0
line_width: null
lr0: 0.0001
lrf: 0.01
mask_ratio: 4
max_det: 15
mixup: 0.1
mode: train
model: yolo11m.pt
momentum: 0.937
mosaic: 0.1
multi_scale: false
name: yoloedge
nbs: 64
nms: false
opset: null
optimize: false
optimizer: AdamW
overlap_mask: true
patience: 100
perspective: 0.0
plots: true
pose: 12.0
pretrained: true
profile: false
project: project1
rect: false
resume: false
retina_masks: false
save: true
save_conf: false
save_crop: false
save_frames: false
save_json: false
save_period: -1
save_txt: false
scale: 0.15
seed: 0
shear: 0.1
show: false
show_boxes: true
show_conf: true
show_labels: true
simplify: true
single_cls: false
source: null
split: val
stream_buffer: false
task: detect
time: null
tracker: botsort.yaml
translate: 0.05
val: true
verbose: true
vid_stride: 1
visualize: false
warmup_bias_lr: 0.1
warmup_epochs: 0.0
warmup_momentum: 0.8
weight_decay: 0.0005
workers: 8
workspace: null
